/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp7labi.vistas;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFormularios = new javax.swing.JMenu();
        jmiFormInscripcion = new javax.swing.JMenuItem();
        jmiFormAlumnos = new javax.swing.JMenuItem();
        jmiFormMaterias = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalirDelSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jmFormularios.setText("Formularios");

        jmiFormInscripcion.setText("Formulario de inscripción");
        jmiFormInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormInscripcionActionPerformed(evt);
            }
        });
        jmFormularios.add(jmiFormInscripcion);

        jmiFormAlumnos.setText("Formulario de alumnos");
        jmiFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormAlumnosActionPerformed(evt);
            }
        });
        jmFormularios.add(jmiFormAlumnos);

        jmiFormMaterias.setText("Formulario de materias");
        jmiFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormMateriasActionPerformed(evt);
            }
        });
        jmFormularios.add(jmiFormMaterias);

        jMenuBar1.add(jmFormularios);

        jmSalir.setText("Salir");

        jmiSalirDelSistema.setText("Salir del sistema");
        jmiSalirDelSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirDelSistemaActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalirDelSistema);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormMateriasActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        ViewFormMaterias vm = new ViewFormMaterias(/*materias*/);
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
        
    }//GEN-LAST:event_jmiFormMateriasActionPerformed
    
    private void jmiSalirDelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirDelSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirDelSistemaActionPerformed

    private void jmiFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormAlumnosActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        ViewFormAlumnos va = new ViewFormAlumnos();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
        
    }//GEN-LAST:event_jmiFormAlumnosActionPerformed

    private void jmiFormInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormInscripcionActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        ViewFormInscripcion vi = new ViewFormInscripcion();
        vi.setVisible(true);
        escritorio.add(vi);
        escritorio.moveToFront(vi);
        
    }//GEN-LAST:event_jmiFormInscripcionActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmFormularios;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiFormAlumnos;
    private javax.swing.JMenuItem jmiFormInscripcion;
    private javax.swing.JMenuItem jmiFormMaterias;
    private javax.swing.JMenuItem jmiSalirDelSistema;
    // End of variables declaration//GEN-END:variables
}
